name: flutter_mapbox_animarker
description: "A Flutter package for smoothly animating markers with position and rotation on Mapbox maps, ideal for tracking real-time movement like vehicles or users images."
version: 0.0.7
repository: https://github.com/sKY02644/flutter_mapbox_animaker

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mapbox_maps_flutter: ^2.2.0
  image: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4


flutter:
  assets:
    - assets/images/