name: flutter_mapbox_animaker
description: "A Flutter package for animating markers on a Mapbox map."
version: 0.0.2
repository: https://github.com/sKY02644/flutter_mapbox_animaker

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mapbox_maps_flutter: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4


flutter:
  assets:
    - assets/images/